apiVersion: v1
kind: Secret
metadata:
  name: niitsyllabriq-secrets
  namespace: niitsyllabriq
type: Opaque
stringData:
  DATABASE_URL: "__DATABASE_URL__"
  JWT_SECRET_KEY: "__JWT_SECRET_KEY__"
  AWS_ACCESS_KEY_ID: "__SPACES_ACCESS_KEY__"
  AWS_SECRET_ACCESS_KEY: "__SPACES_SECRET_KEY__"
  SPACES_ENDPOINT: "__SPACES_ENDPOINT__"
  SPACES_BUCKET_TRAINING: "__SPACES_BUCKET_TRAINING__"
  SPACES_BUCKET_REQUIREMENTS: "__SPACES_BUCKET_REQUIREMENTS__"
  SPACES_BUCKET_EXPORTS: "__SPACES_BUCKET_EXPORTS__"
